//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(sprite)

const palette_color_t sprite_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	
};

const uint8_t sprite_tiles[32] = {
	0x18,0x00,0x1c,0x00,
	0xfe,0x00,0xff,0x00,
	0xff,0x00,0xfe,0x00,
	0x1c,0x00,0x18,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00
	
};

const metasprite_t sprite_metasprite0[] = {
	METASPR_ITEM(-8, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const sprite_metasprites[1] = {
	sprite_metasprite0
};
